export var list = [
  {
    id: 'a1',
    title: "Nội Thất",
    value: [
      {
        id: "a11",
        title2: "Nội Thất Căn Hộ",
        link: "",
        value: [],
      },
      {
        id: "a12",
        title2: " Nội Thất Biên Hòa",
        link: "",
        value: [
          { title3: "sofa Biên Hòa", value: [], id: "a121", link: "" },
          { title3: "Thảm Sofa Biên Hòa", value: [], id: "a122", link: "" },
          { title3: "Kệ TiVi Biên Hòa", value: [], id: "a123", link: "" },
          { title3: "Rèm Cửa Biên Hòa", value: [], id: "a124", link: "" },
          { title3: "Gường Ngủ Biên Hòa ", value: [], id: "a125", link: "" },
          { title3: "Tủ Bếp Biên Hòa", value: [], id: "a126", link: "" },
          { title3: " Bàn Ghế Ăn Biên Hòa ", value: [], id: "a127", link: "" },
          { title3: "Giường Tần Biên Hòa", value: [], id: "a128", link: "" },
          { title3: " Đồ Gỗ Biên Hòa ", value: [], id: "a129", link: "" },
        ],
      },
      {
        id: "a13",
        title2: "Nội Thất Bình Dương",
        link: "",
        value: [
          { title3: "sofa Bình Dương", value: [], id: "a131", link: "" },
          { title3: "Thảm Sofa Bình Dương", value: [], id: "a132", link: "" },
          { title3: "Kệ TiVi Bình Dương", value: [], id: "a133", link: "" },
          { title3: "Rèm Cửa Bình Dương", value: [], id: "a134", link: "" },
          { title3: "Gường Ngủ Bình Dương ", value: [], id: "a135", link: "" },
          { title3: "Tủ Bếp Bình Dương", value: [], id: "a136", link: "" },
          { title3: " Bàn Ghế Ăn Bình Dương ", value: [], id: "a137", link: "" },
          { title3: "Giường Tần Bình Dương", value: [], id: "a138", link: "" },
          { title3: " Đồ Gỗ Bình Dương ", value: [], id: "a139", link: "" },
        ],
      },
      {
        id: "a14",
        title2: "Nội Thất Long An",
        link: "",
        value: [
          { title3: "sofa Long An", value: [], id: "a141", link: "" },
          { title3: "Thảm Sofa Long An", value: [], id: "a142", link: "" },
          { title3: "Kệ TiVi Long An", value: [], id: "a143", link: "" },
          { title3: "Rèm Cửa Long An", value: [], id: "a144", link: "" },
          { title3: "Gường Ngủ Long An ", value: [], id: "a145", link: "" },
          { title3: "Tủ Bếp Long An", value: [], id: "a146", link: "" },
          { title3: " Bàn Ghế Ăn Long An ", value: [], id: "a147", link: "" },
          { title3: "Giường Tần Long An", value: [], id: "a148", link: "" },
          { title3: " Đồ Gỗ Long An ", value: [], id: "a149", link: "" },
        ],
      },
    ],
  },
  {
    id: "b2",
    title: "Thiết Kế Nội Thất",
    value: [
      {
        id: "b2.1",
        title2: "Thiết kế nội thất",
        link: "",
        value: [],
      },
      {
        id: "b2.2",
        title2: "Thi công nội thất",
        link: "",
        value: [],
      },
      {
        id: "b2.3",
        title2: "Thiết Kế Căn Hộ Cho Thuê",
        link: "",
        value: [],
      },
      {
        id: "b2.4",
        title2: "Thi Công Nội Thất Trọn Gói",
        link: "",
        value: [],
      },
      {
        id: "b2.5",
        title2: "Thiết Kế Thi Công Nội Thất Chung Cư",
        link: "",
        value: [],
      },
    ],
  },
  {
    id: "c3",
    title: "Phòng Khách",
    value: [
      {
        id: "c3.1",
        title2: "Bàn Ghế Sofa",
        link: "",
        value: [],
      },
      {
        id: "c3.2",
        title2: "Bàn Sofa Giá Rẻ",
        link: "",
        value: [],
      },
      {
        id: "c3.3",
        title2: "Kệ Tivi",
        link: "",
        value: [],
      },
      {
        id: "c3.4",
        title2: "Kệ Sách Giá Rẻ",
        link: "",
        value: [],
      },
      {
        id: "c3.5",
        title2: "Rèm Màng Cửa Sổ",
        link: "",
        value: [],
      },
      {
        id: "c3.6",
        title2: "Tủ Giày Giá Rẻ",
        link: "",
        value: [],
      },
      {
        id: "c3.7",
        title2: "Thảm Sofa",
        link: "",
        value: [],
      },
      {
        id: "c3.8",
        title2: "Vách Ngăn",
        link: "",
        value: [],
      },
    ],
  },
  {
    id: "d4",
    title: "Phòng Bếp",
    value: [
      {
        id: "d4.1",
        title2: "Tủ Bếp",
        link: "",
        value: [],
      },
      {
        id: "d4.2",
        title2: "Bàn Ghế Ăn",
        link: "",
        value: [],
      },
      {
        id: "d4.3",
        title2: "Quầy Bar",
        link: "",
        value: [],
      },
      {
        id: "d4.4",
        title2: "Phụ Kiện Bếp",
        link: "",
        value: [],
      },
    ],
  },
  {
    id: "e5",
    title: "Phòng Ngủ",
    value: [
      {
        id: "e5.1",
        title2: "Tủ Quần Áo",
        link: "",
        value: [],
      },
      {
        id: "e5.2",
        title2: "Gường Ngủ Giá Rẻ",
        link: "",
        value: [],
      },
      {
        id: "e5.3",
        title2: "Giường Tầng Giá Rẻ",
        link: "",
        value: [],
      },
      {
        id: "e5.4",
        title2: "Gường Ngủ Cho Bé",
        link: "",
        value: [],
      },
      {
        id: "e5.5",
        title2: "Bàn Trang Điểm",
        link: "",
        value: [],
      },
      {
        id: "e5.6",
        title2: "Sàn Gỗ Giá Rẻ",
        link: "",
        value: [],
      },
      {
        id: "e5.7",
        title2: "Nệm Giá Rẻ",
        link: "",
        value: [],
      },
    ],
  },
  {
    id: "f6",
    title: "Văn Phòng",
    value: [
      {
        id: "f6.1",
        title2: "Thiết Kế Nội Thất Văn Phòng",
        link: "",
        value: [],
      },
      {
        id: "f6.2",
        title2: "Bàn Làm Việc",
        link: "",
        value: [],
      },
      {
        id: "f6.3",
        title2: "Ghế Văn Phòng",
        link: "",
        value: [],
      },
    ],
  },
  {
    id: "g7",
    title: "Cafe / Bar",
    value: [
      {
        id: "g7.1",
        title2: "Quầy Bar Cafe",
        link: "",
        value: [],
      },
      {
        id: "g7.2",
        title2: "Ghế Bar Giá Rẻ",
        link: "",
        value: [],
      },
      {
        id: "g7.3",
        title2: "Bàn cafe Giá Rẻ",
        link: "",
        value: [],
      },
      {
        id: "g7.4",
        title2: "Ghế Cafe Giá Rẻ",
        link: "",
        value: [],
      },
    ],
  },
];
